name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build Docker Image and Push
      - name: Build Docker Image and Push
        run: |
          export DOCKER_BUILDKIT=1
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/llm:latest
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -t $IMAGE_NAME --push .

      - name: Build Docker Image and Push
        run: |
          export DOCKER_BUILDKIT=1
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/llm:latest
          docker buildx build \
            --build-arg HUGGING_FACE_TOKEN=${{ secrets.HUGGING_FACE_TOKEN }} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t $IMAGE_NAME \
            --push .
